use_frameworks!

platform :ios, '9.0'

target 'FYFNetworking_Example' do
  pod 'FYFNetworking', :path => '../'

  target 'FYFNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
